apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-test2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test Page 2</title>
    </head>
    <body>
        <h1>test2</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test2
  template:
    metadata:
      labels:
        app: nginx-test2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-index-html-test2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-test2

